version: "3.8"
services:
  mysql:
      image: mysql:8.0
      container_name: mysql_tutorial
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: db_practice
      volumes:
        - dbdata:/var/lib/mysql
      ports:
        - 3305:3306

volumes:
  dbdata: